language: node_js

node_js:
  - '8'

install:
  - npm install

cache:
  directories:
    - node_modules

script:
    - npm install
    - npm install typescript -g
    - tsc
    - npm prune
    - npm install -g serverless
